# name and ip:port should be unique
# to add more peers or clients: add new lines following the same structure
peers:
  - name: 1
    address: 0.0.0.0:10000
    gaddress: 0.0.0.0:12000
  - name: 2
    address: 0.0.0.0:10001
    gaddress: 0.0.0.0:12001
  - name: 3
    address: 0.0.0.0:10002
    gaddress: 0.0.0.0:12002
  - name: 4
    address: 0.0.0.0:10003
    gaddress: 0.0.0.0:12003
  - name: 5
    address: 0.0.0.0:10004
    gaddress: 0.0.0.0:12004
clients:
  - name: 11
    address: 0.0.0.0:11000
    gaddress: 0.0.0.0:14000
  - name: 12
    address: 0.0.0.0:11001
    gaddress: 0.0.0.0:14001
  - name: 13
    address: 0.0.0.0:11002
    gaddress: 0.0.0.0:14002
  - name: 14
    address: 0.0.0.0:11003
    gaddress: 0.0.0.0:14003
  - name: 15
    address: 0.0.0.0:11004
    gaddress: 0.0.0.0:14004